modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="icesculptures"
version="${file.jarVersion}"
displayURL="https://github.com/hnOsmium0001/IceSculptures/"
issueTrackerURL="https://github.com/hnOsmium0001/IceSculptures/issues"
authors="hnOsmium0001"
displayName="Ice Sculptures"
description='''
'''

[[dependencies.icesculptures]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"

[[dependencies.icesculptures]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"
